using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;
using Entities.Models;
using System.Data.Entity.Migrations;

namespace MyDatabase.Initializers
{
    public class MockupDbInitializer : DropCreateDatabaseAlways<ApplicationDbContext>
    {
        protected override void Seed(ApplicationDbContext context)
        {
            ColorFormula f1 = new ColorFormula() { FormulaName = "Fire", Cost = 10, CreationDate = DateTime.Now, Duration = "20", ServiceType = "All Over", FormulasPhotosUrl= "\\Photos\\redHair.jpg" };
            ColorFormula f2 = new ColorFormula() { FormulaName = "Ice", Cost = 20, CreationDate = DateTime.Now, Duration = "30", ServiceType = "Roots", FormulasPhotosUrl = "\\Photos\\whiteHair.jpg" };
            ColorFormula f3 = new ColorFormula() { FormulaName = "Desert", Cost = 30, CreationDate = DateTime.Now, Duration = "40", ServiceType = "All Over", FormulasPhotosUrl = "\\Photos\\blondeHair.jpg" };
            ColorFormula f4 = new ColorFormula() { FormulaName = "Sky", Cost = 40, CreationDate = DateTime.Now, Duration = "50", ServiceType = "Length", FormulasPhotosUrl = "\\Photos\\skyBlue.jpg" };
            ColorFormula f5 = new ColorFormula() { FormulaName = "Sea", Cost = 50, CreationDate = DateTime.Now, Duration = "60", ServiceType = "Strands", FormulasPhotosUrl = "\\Photos\\seaBlue.jpg" };

            #region product
            Product p1 = new Product() { Brand = "Vella", ColorCode = "6.0", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 5, };
            Product p2 = new Product() { Brand = "Loreal", ColorCode = "5.8", ExpDate = DateTime.Now, TubeQuantity = 55.0, UsedQuantity = 4 };
            Product p3 = new Product() { Brand = "Herbal Essences", ColorCode = "7.5", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 3 };
            Product p4 = new Product() { Brand = "Garnier", ColorCode = "2.2", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 2 };
            Product p5 = new Product() { Brand = "Mamaearth", ColorCode = "5.7", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 6 };
            Product p6 = new Product() { Brand = "Biotique", ColorCode = "3.9", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 4 };
            Product p7 = new Product() { Brand = "Kevin", ColorCode = "9.8", ExpDate = DateTime.Now, TubeQuantity = 50.0, UsedQuantity = 4 };
            //p1.Formulas = new List<ColorFormula>() { f1, f2 };
            //p2.Formulas = new List<ColorFormula>() { f3, f4 };
            //p3.Formulas = new List<ColorFormula>() { f4, f5 };
            //p4.Formulas = new List<ColorFormula>() { f4, f5 };
            //p5.Formulas = new List<ColorFormula>() { f1, f2 };
            //p6.Formulas = new List<ColorFormula>() { f2, f3 };

            context.Products.AddOrUpdate(p1, p2, p3, p4, p5, p6, p7);
            context.SaveChanges();
            #endregion

            #region Formulas

            f1.Products = new List<Product>() { p1, p2 };
            f2.Products = new List<Product>() { p3 };
            f3.Products = new List<Product>() { p4 };          
            f4.Products = new List<Product>() { p5 };
            f5.Products = new List<Product>() { p6,p7 };
           
            context.ColorFormulas.AddOrUpdate(f1, f2, f3, f4, f5);
            context.SaveChanges();
            #endregion

            #region Customers
            Customer c1 = new Customer() { FullName = "Οικονόμου Νίκος", Email = "nikosoikonomou@gmail.com", PhoneNumber = "69745645314", PhotoUrl= "\\Photos\\Nikolas.jpg" };
            Customer c2 = new Customer() { FullName = "Οικονόμου Κώστας", Email = "cgeconomou@hotmail.com", PhoneNumber = "69745645679", PhotoUrl = "\\Photos\\Kwstas.jpg" };
            Customer c3 = new Customer() { FullName = "Μαστρογιάννης Θανάσης", Email = "mastrogiannisath@gmail.com", PhoneNumber = "69744545654", PhotoUrl= "\\Photos\\Tanasis.jpg"  };

            c1.FormulaIds = new List<int?>();
            c2.FormulaIds = new List<int?>();
            c3.FormulaIds = new List<int?>();
            context.Customers.AddOrUpdate(c1, c2, c3);
            context.SaveChanges();
            #endregion

            #region ShopProducts
            ShopProduct m1 = new ShopProduct() { Name = "Τροχοί Ονυχοπλαστικής", Category = "Ονυχοπλαστική", Quantity = 10, Price = 8.15, Description = "Φρεζάκι νυχιών καρβιδίου σε κυλινδρικό σχήμα με λεία ή στρογγυλεμένη (safety) κεφαλή, ιδανική για αφαίρεση υλικού, pedicure ή σχηματισμό νυχιού. Οι φρέζες καρβιδίου έχουν μεγάλη αντοχή, είναι αρκετά σκληρές και μπορούν να αποστειρωθούν. Ειναι ιδανικές για την αφαίρεση ημιμόνιμου, gel και ακρυλικού.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/023937/23937854/xlarge_20220210133912_agc_frezaki_12_trocholithakia_onychoplastikis.jpeg" };
            ShopProduct m2 = new ShopProduct() { Name = "Αποροφητήρας νυχιών", Category = "Ονυχοπλαστική", Quantity = 10, Price = 25.55, Description = "Επαγγελματικό φουρνάκι νυχιών με 4 λάμπες UV 36W για στέγνωμα σε 45 δευτερόλεπτα. Είναι κατάλληλο για ημιμόνιμο μανικιούρ / πεντικιούρ.", PhotoUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFWHMf6nNIXq5VTok_JTdyD4nKjLEsxUDSy_myhmNrORVpZ1zyn1esVCL_162jZ8wDA3I&usqp=CAU" };
            ShopProduct m3 = new ShopProduct() { Name = "Αερογράφοι", Category = "Ονυχοπλαστική", Quantity = 10, Price = 11.45, Description = "Αερογράφος mini +αεροσυμπιεστής + 12 φιαλίδια βαφής. Έτοιμο προς χρήση κιτ, περιέχει 12 φιαλίδια ακρυλικής βαφής. Ένας πολύ εύχρηστος, εξαιρετικά αθόρυβος και μικρού μεγέθους συμπιεστής, με μπαταρία.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/033648/33648134/xlarge_20220128113121_aerografos_aerosympiestis_me_12_fialidia_vafis_kas_10219.jpeg" };
            ShopProduct m4 = new ShopProduct() { Name = "Gel Δόμησης", Category = "Ονυχοπλαστική", Quantity = 10, Price = 9.99, Description = "Τζελ στεγανοποίησης ηλεκτρικών συνδέσεων 1000 gr RAY TECH TECHNO GEL GUM μπλε για πισίνες 21kV/mm | Techno Gel Gum", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/036467/36467897/xlarge_20220607161019_tzel_steganopoiisis_ilektrikon_syndeseon_1000_gr_ray_tech_techno_gel_gum_mple_gia_pisines_21kv_mm_techno_gel_gum.jpeg" };
            ShopProduct m5 = new ShopProduct() { Name = "Nail Art", Category = "Ονυχοπλαστική", Quantity = 10, Price = 3.55, Description = "Αμέτρητες δημιουργίες χρωμάτων, με διαφορετικά χρώματα στη βάση ή και χωρίς καθόλου χρώμα, μόνο με κολλώδη ουσία. Συσκευασία : 6 βαζάκια σε σακουλάκι με ασφαλές κλείσιμο.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/031275/31275895/xlarge_20210927141237_aurora_mermaid_skoni_diakosmisis_se_diafora_chromata.jpeg" };
            ShopProduct m6 = new ShopProduct() { Name = "Color Gel", Category = "Ονυχοπλαστική", Quantity = 10, Price = 10.50, Description = "Ιριδίζον gel για πολύ έντονο μαύρισμα.Εφαρμόστε ομοιόμορφα άφθονη ποσότητα σε όλο το σώμα και επαναλάβετε τακτικά, ειδικά μετά το κολύμπι, το σκούπισμα και την εφίδρωση. Αποφύγετε την περιοχή των ματιών.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/003433/3433747/xlarge_20211014125408_carroten_gold_shimmer_tanning_gel_150ml.jpeg" };
            ShopProduct m7 = new ShopProduct() { Name = "Υγρά Νυχιών", Category = "Ονυχοπλαστική", Quantity = 10, Price = 2.99, Description = "Υγρό εμποτισμού που συμβάλλει στη διαμόρφωση του Quickgel Agryl Gel σε φυσική πλάκα νυχιού και σε dual forms", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/027223/27223009/xlarge_20210226181620_quickgel_ygro_akrylikou_liquid_acryl_gel_120ml.jpeg" };
            ShopProduct m8 = new ShopProduct() { Name = "Λίμες", Category = "Ονυχοπλαστική", Quantity = 10, Price = 15.99, Description = "Buffer για τη λείανση της επιφάνειας του νυχιού σε grit 100/180.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/026264/26264948/xlarge_20201216104838_bluesky_nail_file_buffer_100_180_black.jpeg" };
            ShopProduct m9 = new ShopProduct() { Name = "Νύχια κασετίνα", Category = "Ονυχοπλαστική", Quantity = 10, Price = 4.67, Description = "Επαγγελματική κασετίνα με τεχνητά νύχια σε λευκό χρώμα. Η κασετίνα περιέχει 100 νύχια.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/025580/25580430/xlarge_20201110092751_ro_ro_accessories_kasetina_nychion_leyka_100tmch.jpeg" };
            ShopProduct m10 = new ShopProduct() { Name = "Πινέλα", Category = "Ονυχοπλαστική", Quantity = 10, Price = 17.80, Description = "Σετ πινέλων σε θήκη, με 7 μεγάλα πινέλα και 9 μικρά. Έχουν απαλή συνθετική τρίχα και δε μαδάνε.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/026197/26197523/xlarge_20210105143952_anjou_16_epagelmatika_pinela_makigiaz_me_thiki.jpeg" };
            ShopProduct m11 = new ShopProduct() { Name = "Λακ Μαλλιών Spray", Category = "Styling", Quantity = 10, Price = 7.56, Description = "Υγρό προϊόν για φιξάρισμα ακριβείας και δυνατό κράτημα. Προσφέρει ενισχυμένο φιξάρισμα ακριβείας, χωρίς να αφήνει κατάλοιπα στα μαλλιά. Χαρίζει φυσική λάμψη και είναι ιδανικό για βραδινά και απαιτητικά χτενίσματα. Παρέχει αντιηλιακή προστασία από τις ακτίνες UV.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/007847/7847179/xlarge_20151111121627_l_oreal_tecni_art_fix_design_200ml.jpeg" };
            ShopProduct m12 = new ShopProduct() { Name = "Glitter", Category = "Styling", Quantity = 10, Price = 3.45, Description = "Διάφανο glitter νυχιών, ιδανικό για για τη διακόσμηση φυσικών και τεχνητών νυχιών.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/026947/26947193/xlarge_20210204112610_uplac_glitter_448_5g.jpeg" };
            ShopProduct m13 = new ShopProduct() { Name = "Pomade", Category = "Styling", Quantity = 10, Price = 15.95, Description = "Πομάδα για μέτριο κράτημα και ματ αποτέλεσμα, που φεύγει εύκολα με το λούσιμο.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/014154/14154382/xlarge_20180227100229_uppercut_deluxe_matt_pomade_100gr.jpeg" };
            ShopProduct m14 = new ShopProduct() { Name = "Λάκ με χρώμα", Category = "Styling", Quantity = 10, Price = 12.45, Description = "Μόνιμη βαφή μαλλιών της Labor Pro Hair σε καστανή απόχρωση, που επιτρέπει σε σημαντικό βαθμό την αλλαγή χρώματος στα μαλλιά, καλύπτοντας τις λευκές τρίχες και χαρίζοντας διάρκεια.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/037239/37239592/xlarge_20220720132250_lak_me_chroma_kastano_e690c_touch_up_75ml.jpeg" };
            ShopProduct m15 = new ShopProduct() { Name = "Κερί Μαλλιών", Category = "Styling", Quantity = 10, Price = 5.50, Description = "Κερί με απόδοση κρέμας, για απεριόριστες δυνατότητες style.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/008918/8918341/xlarge_20200312161405_schwarzkopf_osis_flexwax_cream_wax_85ml.jpeg" };
            ShopProduct m16 = new ShopProduct() { Name = "Gel Μαλλιών", Category = "Styling", Quantity = 10, Price = 7.00, Description = "Το προϊόν styling Schwarzkopf Professional Osis+ Rock Hard τονίζει το χτένισμά σας και το διατηρεί για μεγάλο χρονικό διάστημα.Οι χρήστες που το έχουν αγοράσει το ξεχωρίζουν κυρίως γιατί έχει μεγάλη διάρκεια και έχει δυνατό κράτημα.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/010558/10558766/xlarge_20200312115602_schwarzkopf_professional_osis_rock_hard_4_150ml.jpeg" };
            ShopProduct m17 = new ShopProduct() { Name = "Κραγιόν Μαλλιών", Category = "Styling", Quantity = 10, Price = 3.89, Description = "Προσωρινή βαφή μαλλιών χωρίς αμμωνία της Golden Rose, που επιτρέπει τη διακριτική αλλαγή απόχρωσης μέχρι το επόμενο λούσιμο, χωρίς να αλλάζει το χρώμα των μαλλιών. Δεν περιέχει αµµωνία, η οποία έχει αντικατασταθεί από άλλο αλκαλικό παράγοντα ή έλαιο, πιο φιλικό προς τα μαλλιά, το δέρμα και τα μάτια.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/012584/12584237/xlarge_20210302092121_golden_rose_gray_hair_touch_up_stick_01_black.jpeg" };
            ShopProduct m18 = new ShopProduct() { Name = "Προϊόντα Όγκου", Category = "Styling", Quantity = 10, Price = 90.00, Description = "Το σετ περιέχει: Sarynakey Pure Africa Shea Damage Repair Light Shampoo 500ml, Λάδι μαλλιών Sarynakey Pure Africa Shea Damage Repair Light Oil 110ml & Μάσκα εντατικής Θεραπείας SarynaKey Pure Africa Shea Damage Repair Light Butter 500ml", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/031966/31966970/xlarge_20211027130903_saryna_key_trio_goes_deeper_lightweight_volume_light_shampoo_500ml_light_oil_110ml_light_butter_500ml.jpeg" };
            ShopProduct m19 = new ShopProduct() { Name = "Υγρές Λάκ", Category = "Styling", Quantity = 10, Price = 8.69, Description = "Υγρό προϊόν για φιξάρισμα ακριβείας και δυνατό κράτημα. Προσφέρει ενισχυμένο φιξάρισμα ακριβείας, χωρίς να αφήνει κατάλοιπα στα μαλλιά. Χαρίζει φυσική λάμψη και είναι ιδανικό για βραδινά και απαιτητικά χτενίσματα. Παρέχει αντιηλιακή προστασία από τις ακτίνες UV.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/019027/19027686/xlarge_20220118085916_l_oreal_tecni_art_fix_design_5_1000ml.jpeg" };
            ShopProduct m20 = new ShopProduct() { Name = "Αφροί Μαλλιών", Category = "Styling", Quantity = 10, Price = 5.96, Description = "Αφρός μαλλιών για μέγιστο όγκο και κράτημα, ενώ περιέχει φίλτρο UV που προστατεύει το χρώμα.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/007861/7861495/xlarge_20200311160226_schwarzkopf_silhouette_color_brilliance_super_hold_mousse_500ml.jpeg" };
            ShopProduct m21 = new ShopProduct() { Name = "Gift Set", Category = "Καλλυντικά", Quantity = 10, Price = 45.87, Description = "Πακέτο περιποίησης με καλλυντικά, της εταιρείας Atache, ιδανικό για όλους τους τύπους επιδερμίδας.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/007329/7329182/xlarge_20200221155518_atache_set_c_vital_serum_active_fluid.jpeg" };
            ShopProduct m22 = new ShopProduct() { Name = "Σώμα", Category = "Καλλυντικά", Quantity = 10, Price = 13.43, Description = "Γαλάκτωμα σώματος κατά της ξηρότητας. Περιέχει λιπίδια και απορροφάται άμεσα από την ξηρή επιδερμίδα, ενισχύοντας τον επιδερμιδικό φραγμό και προστατεύοντας την επιδερμίδα από εξωτερικές επιδράσεις. Ο επιδερμιδικός φραγμός αποκαθίσταται και ανακτά τη φυσική προστατευτική του λειτουργία", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/014956/14956747/xlarge_20180517141957_la_roche_posay_lipikar_lait_750ml.jpeg" };
            ShopProduct m23 = new ShopProduct() { Name = "Παλέτες Μακιγίαζ", Category = "Καλλυντικά", Quantity = 10, Price = 17.88, Description = "Μοναδική παλέτα τριών αποχρώσεων bronzer, highlighter & ρουζ, εμπλουτισμένη με εκχυλίσματα από κουρκουμά και ανανά, για χρώμα υγείας και φυσικά λαμπερό αποτέλεσμα. Χωρίς Mineral Oil, Parabens, Propylene Glycol, Ethanolamines.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/022483/22483362/xlarge_20200416123509_korres_bronze_glow_palette_candy_glow.jpeg" };
            ShopProduct m24 = new ShopProduct() { Name = "Μάτια", Category = "Καλλυντικά", Quantity = 10, Price = 5.76, Description = "Παλέτα με αποχρώσεις που συνδυάζονται μεταξύ τους με διάρκεια. Εφαρμόστε τις σκιές στα βλέφαρα χρησιμοποιώντας ένα πινέλο και δημιουργήστε το επιθυμητό μακιγιάζ.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/015854/15854939/xlarge_20220110160717_revolution_beauty_re_loaded_eye_paleta_skion_mation_velvet_rose_16_5gr.jpeg" };
            ShopProduct m25 = new ShopProduct() { Name = "Βερνίκια νυχιών", Category = "Καλλυντικά", Quantity = 10, Price = 4.55, Description = "Βερνίκι νυχιών με υφή gel που προσφέρει λάμψη, μέγιστη διάρκεια και ημιμόνιμο αποτέλεσμα.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/013109/13109254/xlarge_20171020163137_korres_gel_effect_nail_colour_100_black.jpeg" };
            ShopProduct m26 = new ShopProduct() { Name = "Χείλη", Category = "Καλλυντικά", Quantity = 10, Price = 5.99, Description = "Τονωτικό gloss χειλιών της Maybelline που έχει δημιουργηθεί για να ενυδατώνει και να χαρίζει πλούσια, λαμπερά χείλη. Θα φαίνονται πιο φυσικά χάρη στην αυξημένη ποσότητα του απαραίτητου νερού που αποτρέπει την ξηρότητα και τα σκασμένα χείλη.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/025993/25993626/xlarge_20201202124118_maybelline_lifter_gloss_009_topaz.jpeg" };
            ShopProduct m27 = new ShopProduct() { Name = "Φρύδια", Category = "Καλλυντικά", Quantity = 10, Price = 8.80, Description = "Τα συστατικά που εμπεριέχονται στην φόρμουλα κατασκευής του προϊόντος συμβάλλουν στην ανάπτυξη των τριχών. Θρέφουν και προστατεύουν τις βλεφαρίδες. Απλή εφαρμογή, ασφαλής και διαρκεί περίπου 45 λεπτά.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/021473/21473863/xlarge_20191230112009_refectocil_color_eyelash_eyebrow_shade_black_15ml.jpeg" };
            ShopProduct m28 = new ShopProduct() { Name = "Πρόσωπο", Category = "Καλλυντικά", Quantity = 10, Price = 14.06, Description = "Καλυπτικό make up σε μορφή πούδρας, ιδανικό για τη μικτή και λιπαρή επιδερμίδα.Οι χρήστες που το έχουν αγοράσει το ξεχωρίζουν κυρίως γιατί απλώνεται εύκολα και προσφέρει ικανοποιητική κάλυψη.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/007447/7447776/xlarge_20160315163827_la_roche_posay_toleriane_teint_mineral_13_beige_sand_9_5gr.jpeg" };
            ShopProduct m29 = new ShopProduct() { Name = "Αρώματα", Category = "Καλλυντικά", Quantity = 10, Price = 15.89, Description = "Αρωματικό mist με νότες καρύδας που χαρίζουν ένα τροπικό και φρουτώδες άρωμα ενώ ταυτόχρονα ενυδατώνουν την επιδερμίδα.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/020003/20003604/xlarge_20200527090314_victoria_s_secret_coconut_passion_body_mist_250ml.jpeg" };
            ShopProduct m30 = new ShopProduct() { Name = "Σφουγκαράκια Μακιγίαζ", Category = "Καλλυντικά", Quantity = 10, Price = 9.90, Description = "Πλένεται στο πλυντήριο Περιλαμβάνεται τσάντα ματιών Τριπλά στρώματα Δύο χρησιμοποιήσιμες πλευρές Μίγμα βαμβακερών και ινών μπαμπού Μεγαλύτερα από τα κανονικά μαξιλάρια αφαίρεσης μακιγιάζ ΣΗΜΕΙΩΣΗ: δεν είναι κατάλληλο για βερνίκι νυχιών", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/029748/29748797/xlarge_20210629104646_epanachrisimopoiisima_sfougarakia_afairesis_makigiaz_6tmch.jpeg" };
            ShopProduct m31 = new ShopProduct() { Name = "Άλατα Μπάνιου", Category = "Αισθητική", Quantity = 10, Price = 2.93, Description = "Αυτά τα αναζωογονητικά άλατα μπάνιου είναι εμπλουτισμένα με αιθέρια έλαια και έλαια από βότανα άγριας Συγκομιδής Σιβηρίας και κάνει το δέρμα νεανικά όμορφο.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/012101/12101019/xlarge_20200313131400_natura_siberica_bath_salt_revitalizing_600gr.jpeg" };
            ShopProduct m32 = new ShopProduct() { Name = "Βαφές Φρυδίών", Category = "Αισθητική", Quantity = 10, Price = 9.27, Description = "Το Brow Tattoo είναι μια καινοτομία για φρύδια τέλεια, καλοσχηματισμένα και ομοιόμορφα γεμάτα για έως και 3 μέρες!", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/013172/13172079/xlarge_20200209203413_maybelline_tattoo_brow_3_day_gel_tint_3_dark_brown.jpeg" };
            ShopProduct m33 = new ShopProduct() { Name = "Βλεφαρίδες-Κόλλες", Category = "Αισθητική", Quantity = 10, Price = 7.68, Description = "Αδιάβροχη κόλλα για βλεφαρίδες, σε λευκό χρώμα, που γίνεται διαφανής όταν στεγνώσει. Ειδικά σχεδιασμένη με φόρμουλα latex που δημιουργήθηκε για να διαρκεί όλη μέρα.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/025524/25524192/xlarge_20210312133443_ro_ro_accessories_kolla_vlefaridon_clear_white.jpeg" };
            ShopProduct m34 = new ShopProduct() { Name = "Κιτ Βλεφαρίδων-Φρυδιών", Category = "Αισθητική", Quantity = 10, Price = 10.99, Description = "Ducare Περιποίησης Φρυδιών 5τμχ", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/036030/36030988/xlarge_20220517160422_ducare_peripoiisis_frydion_5tmch.jpeg" };
            ShopProduct m35 = new ShopProduct() { Name = "Εξοπλισμός Αισθητικής", Category = "Αισθητική", Quantity = 10, Price = 40.52, Description = "Labor Pro Hair Vaper Vapo Family 8735021", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/027230/27230995/xlarge_20210219135223_labor_pro_hair_vaper_vapo_family_8735021.jpeg" };
            ShopProduct m36 = new ShopProduct() { Name = "Τσιμπιδάκια Φρυδιών", Category = "Αισθητική", Quantity = 10, Price = 3.77, Description = "Το τσιμπιδάκι αυτό κατασκευάζεται από υψηλής ποιότητας ανοξείδωτο ατσάλι και μπορεί να απολυμανθεί.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/026033/26033782/xlarge_20201203143306_ro_ro_accessories_tsimpidaki_frydion_isio.jpeg" };
            ShopProduct m37 = new ShopProduct() { Name = "Εργαλεία Αισθητικής", Category = "Αισθητική", Quantity = 10, Price = 6.78, Description = "Εκπαιδευτική κούκλα με μακρύ μαλλί με βάση Ποιότητα τρίχας : Συνθετική ΑΑ αρίστης ποιότητας 55/60 cm", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/023397/23397311/xlarge_20200529094345_ekpaideytiki_koukla_me_makry_malli_poiotita_trichas_aa.jpeg" };
            ShopProduct m38 = new ShopProduct() { Name = "Ράσπες-Τρίφτες", Category = "Αισθητική", Quantity = 10, Price = 2.5, Description = "Yanni Extensions Τρίφτης Ράσπα Ποδιών Ξύλινος", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/019730/19730623/xlarge_20190812102457_yanni_extensions_triftis_raspa_podion_xylinos.jpeg" };
            ShopProduct m39 = new ShopProduct() { Name = "Ψαλιδάκια Βλεφαρίδων", Category = "Αισθητική", Quantity = 10, Price = 3.97, Description = "Ψαλίδι βλεφαρίδων σε μωβ χρώμα, με ανταλλακτική βάση σιλικόνης.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/019128/19128144/xlarge_20190620152052_essence_eyelash_curler.jpeg" };
            ShopProduct m40 = new ShopProduct() { Name = "Ποδιές-Κιμονό", Category = "Αισθητική", Quantity = 10, Price = 20.33, Description = "Barber Mood BM-D 114 Ποδιά Κομμωτηρίου σε Μαύρο Χρώμα", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/026245/26245109/fixedratio_20220510235113_barber_mood_bm_d_114_podia_kommotiriou_se_mayro_chroma.jpeg" };
            ShopProduct m41 = new ShopProduct() { Name = "Συσκευές θεραπείας-Παραφίνης", Category = "Αποτρίχωση", Quantity = 10, Price = 150.55, Description = "Giovanni Μηχανή Παραφίνης 220W & Παραφίνες Ροδάκινου 8τμχ", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/023822/23822369/xlarge_20200630110443_giovanni_michani_parafinis_220w_parafines_rodakinou_8tmch.jpeg" };
            ShopProduct m42 = new ShopProduct() { Name = "Κεριά Αποτρίχωσης", Category = "Αποτρίχωση", Quantity = 10, Price = 15.55, Description = "Ro.ial. Honey Liposoluble Depilatory Wax 800ml", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/009902/9902191/xlarge_20160920162423_ro_ial_keri_apotrichosis_meli_800ml.jpeg" };
            ShopProduct m43 = new ShopProduct() { Name = "Διάφορα Αποτριχωτικά", Category = "Αποτρίχωση", Quantity = 10, Price = 61.21, Description = "Σετ αποτρίχωσης epilator της εταιρείας Braun, κατάλληλο για χρήση στο σώμα και την περιοχή του μπικίνι. Περιλαμβάνει μηχανή με ειδικές περιστρεφόμενες ηλεκτρικές τσιμπίδες μεγάλης ταχύτητας, αφαιρεί από τον θύλακα τις λεπτές ή χοντρές τρίχες κάθε μήκους, προσφέροντας μακροπρόθεσμα αποτελέσματα και απαλότητα στην επιδερμίδα.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/022694/22694166/xlarge_20200407131524_braun_silk_epil_wet_dry_epilator_5_620.jpeg" };
            ShopProduct m44 = new ShopProduct() { Name = "Κεριέρες", Category = "Αποτρίχωση", Quantity = 10, Price = 27.44, Description = "Σετ αποτρίχωσης που περιλαμβάνει 4 ρολέτες κεριού αποτρίχωσης 100ml, 250 ταινίες αποτρίχωσης, λάδι περιποίησης 150ml και συσκευή θέρμανσης.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/016902/16902345/xlarge_20181221142101_peggy_sage_4_cartridge_of_warm_depilatory_wax_kit.jpeg" };
            ShopProduct m45 = new ShopProduct() { Name = "Λάδι Μαλλιών", Category = "Αποτρίχωση", Quantity = 10, Price = 29.79, Description = "Έλαιο πολλαπλών χρήσεων για εκθαμβωτική λάμψη. Είναι ιδανικό για όλους τους τύπους μαλλιών και προσφέρει θρέψη, απαλότητα και εντυπωσιακή λάμψη.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/016636/16636858/xlarge_20200513174215_kerastase_elixir_ultime_l_huile_original_100ml.jpeg" };
            ShopProduct m46 = new ShopProduct() { Name = "Σπάτουλες", Category = "Αποτρίχωση", Quantity = 10, Price = 15.00, Description = "Ανοξείδωτη παλέτα ανάμειξης καλλυντικών σε σχήμα καρδίας με ανοξείδωτη σπάτουλα 2 όψεων. Απαραίτητο αξεσουάρ για κάθε επαγγελματία και όχι μόνο . Το σετ περιλαμβάνει μια παλέτα και μια σπάτουλα ανάμειξης διπλής όψης . Διαστάσεις παλέτας 110x97x1 mm", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/028712/28712636/xlarge_20210506103012_anoxeidoti_paleta_anameixis_kallyntikon_se_schima_kardias_me_anoxeidoti_spatoula_2_opseon.jpeg" };
            ShopProduct m47 = new ShopProduct() { Name = "Χαρτιά Αποτρίχωσης", Category = "Αποτρίχωση", Quantity = 10, Price = 15, Description = "Ρολό αποτρίχωσης για χρήση με κερί ρολέτα. Κατασκευασμένο από πολύ ανθεκτικό συνθετικό ύφασμα non woven που δεν αφήνει χνούδια.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/009259/9259044/xlarge_20200314142919_depilia_non_woven_roll_for_epilation_rollo_apotrichosis_100m.jpeg" };
            ShopProduct m48 = new ShopProduct() { Name = "Γάντια μίας Χρήσης", Category = "Προσωπική Υγεία", Quantity = 10, Price = 9.55, Description = "Εξεταστικά αμφιδέξια γάντια νιτριλίου μιας χρήσης χωρίς πούδρα και μη αποστειρωμένα.Οι χρήστες που τα έχουν αγοράσει τα ξεχωρίζουν κυρίως γιατί ´εχουν καλή εφαρμογή.", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/035484/35484364/xlarge_20220418093734_bournas_medicals_bold_examination_gantia_nitriliou_choris_poudra_se_mayro_chroma_100tmch.jpeg" };
            ShopProduct m49 = new ShopProduct() { Name = "Μάσκες Προστασίας", Category = "Προσωπική Υγεία", Quantity = 10, Price = 1.76, Description = "Μάσκα προστασίας FFP2 από μη υφαντό πολυπροπυλένιο, με ρυθμιζόμενο έλασμα & άνετα ελαστικά στήριξης. Προσφέρει συνεχή εισπνευστική αντίσταση για προστασία με άνεση. Πρότυπο: EN149:2001+A1:2009", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/028365/28365091/xlarge_20210419091530_famex_particle_filtering_half_mask_midnight_midnight_blue_10tmch.jpeg" };
            ShopProduct m50 = new ShopProduct() { Name = "Απολυματικά υγρά", Category = "Προσωπική Υγεία", Quantity = 10, Price = 5.60, Description = "Μαντηλάκια καθαρισμού και απολύμανσης για την ευαίσθητη περιοχή των ματιών. Είναι υποαλλεργικά ελεγμένο, με pH ίδιο με των δακρύων, ρυθμίζει το βακτηριακό φορτίο και είναι κατάλληλο για τον καθημερινό καθαρισμό της περιοχής των ματιών.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/009893/9893600/xlarge_20200224125002_helenvita_blephacare_duo_ygra_mantilakia_14tmch.jpeg" };
            ShopProduct m51 = new ShopProduct() { Name = "Μαντήλια Μαλλιών", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 1.55, Description = "Μαντήλι που μπορεί να φορεθεί ως κορδέλα ή ως μπαντάνα. Σε ποικιλία χρωμάτων και σχεδίων.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/023651/23651179/xlarge_20210421102326_ro_ro_accessories_mantili_mpantana_mple.jpeg" };
            ShopProduct m52 = new ShopProduct() { Name = "Σούρες Μαλλιών", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 2.59, Description = "ΣΟΥΡΑ ΜΑΛΛΙΩΝ ΡΙΓΕ ΠΟΛΥΧΡΩΜΗ", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/035975/35975990/xlarge_20220712162823_soura_mallion_rige_polychromi.jpeg" };
            ShopProduct m53 = new ShopProduct() { Name = "Λάστιχα Μαλλιών", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 5.68, Description = "Συσκευασία από 3 λαστιχάκια με καινοτόμο σχεδιασμό που παρέχουν υψηλή άνεση στη χρήση είτε για τα μαλλιά είτε ως βραχιόλι.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/021559/21559508/xlarge_20200317104610_invisibobble_original_3tmch_pretzel_brown.jpeg" };
            ShopProduct m54 = new ShopProduct() { Name = "Κορδέλες Μαλλιών", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 1.33, Description = "Κορδέλα μαλλιών σε σχεδιασμό λουλουδιών. Είναι κατασκευασμένη από μαλακό και ελαστικό ύφασμα που προσφέρει σταθερότητα και άνεση για όλες τις ώρες της ημέρας.", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/031833/31833428/xlarge_20211020132658_kordela_mallion_me_lasticho_floral_leyki.jpeg" };
            ShopProduct m55 = new ShopProduct() { Name = "Μπαντάνες", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 3.42, Description = "Μπαντάνα πολλαπλών χρήσεων. Κατασκευασμένη απο πολυεστέρα. Χωρίς ραφή ώστε να μην ενοχλεί. Μπορεί να χρησιμοποιηθεί με πολλούς διαφορετικούς τρόπους: στα μαλλιά, σαν περιλαίμιο, μπαλακλάβα, περικάρπιο κλπ. Μέγεθος: one size Διαστάσεις: 46cm x 24cm", PhotoUrl = "https://a.scdn.gr/images/sku_main_images/030842/30842284/xlarge_20210906121242_mpantana_mallion_polympantana.jpeg" };
            ShopProduct m56 = new ShopProduct() { Name = "Τουρμπάνια", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 8.66, Description = "Γυναικείο τουρμπάνι που καλύπτει το κεφάλι, με όμορφα μοτίβα.", PhotoUrl = "https://d.scdn.gr/images/sku_main_images/036397/36397407/xlarge_20220603095006_gynaikeio_tourmpani_emprime_mayro_roz.jpeg" };
            ShopProduct m57 = new ShopProduct() { Name = "Κλάμερ", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 2.12, Description = "Hairutopia Κλάμερ Μαλλιών Καφέ 1τμχ", PhotoUrl = "https://c.scdn.gr/images/sku_main_images/033218/33218689/xlarge_20220114151721_hairutopia_klamer_mallion_kafe_1tmch.jpeg" };
            ShopProduct m58 = new ShopProduct() { Name = "Λάστιχα Διακοσμητικά", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 19.15, Description = "Τα διακοσμητικά σκαλιστά ξύλα της σειράς έχουν μια απίθανη ελαστικότητα. Λυγίζουν όπου ακριβώς θέλετε ώστε να παίρνουν το σχήμα που θέλετε και να τοποθετούνται πάνω σε όποια επιφάνεια έχετε. Όπως κυκλική, εξάγωνη, οκτάγωνη, ακανόνιστη, με καμπύλες ή γωνίες ή ακόμη περιμετρικά σε μπουκάλι.", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/032344/32344696/xlarge_20211115125224_xylino_elastiko_diakosmitiko_kentrou_13ek_ch_5_3ek.jpeg" };
            ShopProduct m59 = new ShopProduct() { Name = "Κλίκ-Κλάκ", Category = "Αξεσουάρ Μαλλιών", Quantity = 10, Price = 2.48, Description = "Ro-Ro Accessories Κλικ Κλακ Μαύρα 7cm Σετ 2τμχ", PhotoUrl = "https://b.scdn.gr/images/sku_main_images/028615/28615577/xlarge_20220705114426_ro_ro_accessories_klik_klak_mayra_7cm_set_2tmch.jpeg" };

            context.ShopProducts.AddOrUpdate(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21, m22, m23, m24, m25, m26, m27, m28, m29, m30, m31, m32, m33, m34, m35, m36, m37, m38, m39, m40, m41, m42, m43, m44, m45, m46, m47, m48, m49, m50, m51, m52, m53, m54, m55, m56, m57, m58, m59);
            context.SaveChanges();


            #endregion

            #region Orders
            Order sc1 = new Order() { FirstName = "Nikos", LastName = "Oikonomou", Email="nikosoikonomou88@gmail.com", Address="Plastira 55", TotalCost = 150 };
            Order sc2 = new Order() { FirstName = "Kwstas", LastName = "Oikonomou", Email="kwstasoikonomou88@gmail.com", Address = "Plastira 45", TotalCost = 140 };
            Order sc3 = new Order() { FirstName = "Thanasis", LastName = "Mastrogiannis", Email="mastrogiannisath@gmail.com", Address = "Plastira 55", TotalCost = 130 };
            context.Orders.AddOrUpdate(sc1, sc2, sc3);
            context.SaveChanges();
            #endregion

            #region WarehouseProducts
            WarehouseProduct whPr1 = new WarehouseProduct() { Brand = "Vella", ColorCode = "1.0",TubeQuantity = 50,TotalQuantity = 250 };
            WarehouseProduct whPr2 = new WarehouseProduct() { Brand = "Vella", ColorCode = "2.0", TubeQuantity = 50,TotalQuantity = 250 }; 
            WarehouseProduct whPr3 = new WarehouseProduct() { Brand = "Vella", ColorCode = "3.0", TubeQuantity = 50,TotalQuantity = 250 }; 
            WarehouseProduct whPr4 = new WarehouseProduct() { Brand = "Vella", ColorCode = "4.0", TubeQuantity = 50,TotalQuantity = 250 }; 
            WarehouseProduct whPr5 = new WarehouseProduct() { Brand = "Vella", ColorCode = "5.0", TubeQuantity = 50,TotalQuantity = 250 }; 
            WarehouseProduct whPr6 = new WarehouseProduct() { Brand = "Vella", ColorCode = "6.0", TubeQuantity = 50, TotalQuantity = 250 };
            WarehouseProduct whPr7 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "1.0", TubeQuantity = 50, TotalQuantity = 350 };
            WarehouseProduct whPr8 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "2.0", TubeQuantity = 50, TotalQuantity = 100 };
            WarehouseProduct whPr9 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "3.0", TubeQuantity = 50, TotalQuantity = 450 };
            WarehouseProduct whPr10 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "4.0", TubeQuantity = 50, TotalQuantity = 900 };
            WarehouseProduct whPr11 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "5.0", TubeQuantity = 50, TotalQuantity = 1250 };
            WarehouseProduct whPr12 = new WarehouseProduct() { Brand = "Kevin Murphy", ColorCode = "6.0", TubeQuantity = 50, TotalQuantity = 50 };
            WarehouseProduct whPr13 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "1.0", TubeQuantity = 50, TotalQuantity = 50 };
            WarehouseProduct whPr14 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "2.0", TubeQuantity = 50, TotalQuantity = 350 };
            WarehouseProduct whPr15 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "3.0", TubeQuantity = 50, TotalQuantity = 500 };
            WarehouseProduct whPr16 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "4.0", TubeQuantity = 50, TotalQuantity = 100 };
            WarehouseProduct whPr17 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "5.0", TubeQuantity = 50, TotalQuantity = 2000 };
            WarehouseProduct whPr18 = new WarehouseProduct() { Brand = "Apivita", ColorCode = "6.0", TubeQuantity = 50, TotalQuantity = 1400 };
            context.WarehouseProducts.AddOrUpdate(whPr1, whPr2, whPr3, whPr4, whPr5, whPr6, whPr7, whPr8, whPr9, whPr10, whPr12, whPr13, whPr14, whPr15, whPr16, whPr17, whPr18);
            context.SaveChanges();
            #endregion

            base.Seed(context);
        }
    }
}
